# Form implementation generated from reading ui file 'FGC_gui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(771, 351)
        Frame.setMinimumSize(QtCore.QSize(771, 351))
        Frame.setMaximumSize(QtCore.QSize(771, 351))
        Frame.setStyleSheet("background-color: none;\n"
"border-radius:20px;")
        Frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame = QtWidgets.QFrame(parent=Frame)
        self.frame.setGeometry(QtCore.QRect(0, 0, 771, 351))
        self.frame.setStyleSheet("QFrame {\n"
"    border-radius:20px;\n"
"    background-color: rgb(6, 0, 83);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.MWEntry = QtWidgets.QLineEdit(parent=self.frame)
        self.MWEntry.setGeometry(QtCore.QRect(10, 280, 181, 61))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(16)
        font.setBold(True)
        self.MWEntry.setFont(font)
        self.MWEntry.setStyleSheet("QLineEdit {\n"
"    border-radius: 10px;\n"
"    background-color: rgb(86, 74, 255);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.MWEntry.setText("")
        self.MWEntry.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.MWEntry.setObjectName("MWEntry")
        self.Widget_FuelGenNeed = QtWidgets.QWidget(parent=self.frame)
        self.Widget_FuelGenNeed.setGeometry(QtCore.QRect(10, 80, 181, 181))
        self.Widget_FuelGenNeed.setStyleSheet("QWidget {\n"
"    background-color:rgb(25, 15, 168);\n"
"    border-radius: 20px\n"
"}")
        self.Widget_FuelGenNeed.setObjectName("Widget_FuelGenNeed")
        self.widget_3 = QtWidgets.QWidget(parent=self.Widget_FuelGenNeed)
        self.widget_3.setGeometry(QtCore.QRect(10, 10, 161, 41))
        self.widget_3.setStyleSheet("background-color: rgb(21, 14, 158);")
        self.widget_3.setObjectName("widget_3")
        self.label_3 = QtWidgets.QLabel(parent=self.widget_3)
        self.label_3.setGeometry(QtCore.QRect(-2, -1, 161, 41))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(14)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color:none;\n"
"color: rgb(255, 255, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.FuelGen_Output = QtWidgets.QLabel(parent=self.Widget_FuelGenNeed)
        self.FuelGen_Output.setGeometry(QtCore.QRect(0, 60, 181, 111))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(22)
        self.FuelGen_Output.setFont(font)
        self.FuelGen_Output.setStyleSheet("color: rgb(255, 255, 255);")
        self.FuelGen_Output.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.FuelGen_Output.setObjectName("FuelGen_Output")
        self.widget_2 = QtWidgets.QWidget(parent=self.frame)
        self.widget_2.setGeometry(QtCore.QRect(480, 280, 281, 61))
        self.widget_2.setStyleSheet("QWidget {\n"
"    background-color:rgb(25, 15, 168);\n"
"    border-radius: 20px\n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.label_2 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 281, 21))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(16)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:none")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.ImpureRadioButton = QtWidgets.QRadioButton(parent=self.widget_2)
        self.ImpureRadioButton.setGeometry(QtCore.QRect(10, 20, 81, 41))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        font.setBold(False)
        self.ImpureRadioButton.setFont(font)
        self.ImpureRadioButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none;")
        self.ImpureRadioButton.setObjectName("ImpureRadioButton")
        self.NormalRadioButton = QtWidgets.QRadioButton(parent=self.widget_2)
        self.NormalRadioButton.setGeometry(QtCore.QRect(110, 20, 81, 41))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        font.setBold(False)
        self.NormalRadioButton.setFont(font)
        self.NormalRadioButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none;")
        self.NormalRadioButton.setObjectName("NormalRadioButton")
        self.PureRadioButton = QtWidgets.QRadioButton(parent=self.widget_2)
        self.PureRadioButton.setGeometry(QtCore.QRect(220, 20, 61, 41))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        font.setBold(False)
        self.PureRadioButton.setFont(font)
        self.PureRadioButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none;")
        self.PureRadioButton.setObjectName("PureRadioButton")
        self.CalculateButton = QtWidgets.QPushButton(parent=self.frame)
        self.CalculateButton.setGeometry(QtCore.QRect(200, 290, 271, 41))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        font.setBold(False)
        self.CalculateButton.setFont(font)
        self.CalculateButton.setStyleSheet("QPushButton {\n"
"    background-color:rgb(25, 16, 181);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:20px\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(32, 24, 255);\n"
"}")
        self.CalculateButton.setObjectName("CalculateButton")
        self.Widget_FuelPerMin = QtWidgets.QWidget(parent=self.frame)
        self.Widget_FuelPerMin.setGeometry(QtCore.QRect(200, 80, 181, 181))
        self.Widget_FuelPerMin.setStyleSheet("QWidget {\n"
"    background-color:rgb(25, 15, 168);\n"
"    border-radius: 20px\n"
"}")
        self.Widget_FuelPerMin.setObjectName("Widget_FuelPerMin")
        self.widget_5 = QtWidgets.QWidget(parent=self.Widget_FuelPerMin)
        self.widget_5.setGeometry(QtCore.QRect(10, 10, 161, 41))
        self.widget_5.setStyleSheet("background-color: rgb(21, 14, 158);")
        self.widget_5.setObjectName("widget_5")
        self.label_4 = QtWidgets.QLabel(parent=self.widget_5)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 161, 41))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(14)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color:none;\n"
"color: rgb(255, 255, 255);")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.FuelPerMin_Output = QtWidgets.QLabel(parent=self.Widget_FuelPerMin)
        self.FuelPerMin_Output.setGeometry(QtCore.QRect(0, 60, 181, 111))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(22)
        self.FuelPerMin_Output.setFont(font)
        self.FuelPerMin_Output.setStyleSheet("color: rgb(255, 255, 255);")
        self.FuelPerMin_Output.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.FuelPerMin_Output.setObjectName("FuelPerMin_Output")
        self.Widget_Ref = QtWidgets.QWidget(parent=self.frame)
        self.Widget_Ref.setGeometry(QtCore.QRect(390, 80, 181, 181))
        self.Widget_Ref.setStyleSheet("QWidget {\n"
"    background-color:rgb(25, 15, 168);\n"
"    border-radius: 20px\n"
"}")
        self.Widget_Ref.setObjectName("Widget_Ref")
        self.widget_7 = QtWidgets.QWidget(parent=self.Widget_Ref)
        self.widget_7.setGeometry(QtCore.QRect(10, 10, 161, 41))
        self.widget_7.setStyleSheet("background-color: rgb(21, 14, 158);")
        self.widget_7.setObjectName("widget_7")
        self.label_5 = QtWidgets.QLabel(parent=self.widget_7)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 161, 41))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(14)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color:none;\n"
"color: rgb(255, 255, 255);")
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.Refineries_Output = QtWidgets.QLabel(parent=self.Widget_Ref)
        self.Refineries_Output.setGeometry(QtCore.QRect(0, 60, 181, 111))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(22)
        self.Refineries_Output.setFont(font)
        self.Refineries_Output.setStyleSheet("color: rgb(255, 255, 255);")
        self.Refineries_Output.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Refineries_Output.setObjectName("Refineries_Output")
        self.Widget_OilExt = QtWidgets.QWidget(parent=self.frame)
        self.Widget_OilExt.setGeometry(QtCore.QRect(580, 80, 181, 181))
        self.Widget_OilExt.setStyleSheet("QWidget {\n"
"    background-color:rgb(25, 15, 168);\n"
"    border-radius: 20px\n"
"}")
        self.Widget_OilExt.setObjectName("Widget_OilExt")
        self.widget_9 = QtWidgets.QWidget(parent=self.Widget_OilExt)
        self.widget_9.setGeometry(QtCore.QRect(10, 10, 161, 41))
        self.widget_9.setStyleSheet("background-color: rgb(21, 14, 158);")
        self.widget_9.setObjectName("widget_9")
        self.label_6 = QtWidgets.QLabel(parent=self.widget_9)
        self.label_6.setGeometry(QtCore.QRect(0, 0, 161, 41))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(14)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color:none;\n"
"color: rgb(255, 255, 255);")
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.OilExt_Output = QtWidgets.QLabel(parent=self.Widget_OilExt)
        self.OilExt_Output.setGeometry(QtCore.QRect(0, 60, 181, 111))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(22)
        self.OilExt_Output.setFont(font)
        self.OilExt_Output.setStyleSheet("color: rgb(255, 255, 255);")
        self.OilExt_Output.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.OilExt_Output.setObjectName("OilExt_Output")
        self.title_bar = QtWidgets.QFrame(parent=self.frame)
        self.title_bar.setGeometry(QtCore.QRect(-1, -1, 771, 51))
        self.title_bar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.title_bar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.title_bar.setObjectName("title_bar")
        self.label = QtWidgets.QLabel(parent=self.title_bar)
        self.label.setGeometry(QtCore.QRect(10, 0, 461, 51))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(24)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.buttons_title_bar = QtWidgets.QFrame(parent=self.title_bar)
        self.buttons_title_bar.setGeometry(QtCore.QRect(670, 10, 91, 41))
        self.buttons_title_bar.setStyleSheet("QFrame {\n"
"    border-radius:20px;\n"
"    background-color: rgb(10, 0, 152);\n"
"}")
        self.buttons_title_bar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.buttons_title_bar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.buttons_title_bar.setObjectName("buttons_title_bar")
        self.CloseButton = QtWidgets.QPushButton(parent=self.buttons_title_bar)
        self.CloseButton.setGeometry(QtCore.QRect(53, 5, 31, 31))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(11)
        font.setBold(True)
        self.CloseButton.setFont(font)
        self.CloseButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(1, 140, 168);\n"
"    border-radius:15px\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(2, 213, 255);\n"
"}")
        self.CloseButton.setObjectName("CloseButton")
        self.MinButton = QtWidgets.QPushButton(parent=self.buttons_title_bar)
        self.MinButton.setGeometry(QtCore.QRect(8, 5, 31, 31))
        font = QtGui.QFont()
        font.setFamily("SF Pro Text")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        self.MinButton.setFont(font)
        self.MinButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(1, 140, 168);\n"
"    border-radius:15px\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(2, 213, 255);\n"
"}")
        self.MinButton.setObjectName("MinButton")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)
        Frame.setTabOrder(self.ImpureRadioButton, self.NormalRadioButton)
        Frame.setTabOrder(self.NormalRadioButton, self.CloseButton)
        Frame.setTabOrder(self.CloseButton, self.PureRadioButton)
        Frame.setTabOrder(self.PureRadioButton, self.MinButton)
        Frame.setTabOrder(self.MinButton, self.MWEntry)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.MWEntry.setPlaceholderText(_translate("Frame", "MW"))
        self.label_3.setText(_translate("Frame", "Fuel Generators"))
        self.FuelGen_Output.setText(_translate("Frame", "0"))
        self.label_2.setText(_translate("Frame", "Oil Rare"))
        self.ImpureRadioButton.setText(_translate("Frame", "Impure"))
        self.NormalRadioButton.setText(_translate("Frame", "Normal"))
        self.PureRadioButton.setText(_translate("Frame", "Pure"))
        self.CalculateButton.setText(_translate("Frame", "Caculate"))
        self.label_4.setText(_translate("Frame", "Fuel Per/Min"))
        self.FuelPerMin_Output.setText(_translate("Frame", "0"))
        self.label_5.setText(_translate("Frame", "Refineries"))
        self.Refineries_Output.setText(_translate("Frame", "0"))
        self.label_6.setText(_translate("Frame", "Oil Extractors"))
        self.OilExt_Output.setText(_translate("Frame", "0"))
        self.label.setText(_translate("Frame", "Fuel Generator Calculator"))
        self.CloseButton.setText(_translate("Frame", "🞫"))
        self.MinButton.setText(_translate("Frame", "-"))
